// Mocked data for categories
const categories = [
  {
    name: "Food Stores",
    description: "Places to eat on and around campus",
    businesses: [
      {
        id: "acme-diner",
        name: "Campus Cafeteria",
        description: "Affordable student meal options",
        phone: "555-0101",
        location: "Student Union Building",
        hours: "7AM - 8PM Weekdays",
        image: "/images/campus-cafe.jpg",
      },
      {
        id: "sushi-delights",
        name: "Faculty Dining Hall",
        description: "Upscale dining for faculty and guests",
        phone: "555-0102",
        location: "Administration Building, 2nd Floor",
        hours: "11AM - 3PM Weekdays",
        image: "/images/faculty-dining.jpg",
      },
      {
        id: "pasta-house",
        name: "The Study Brew",
        description: "Coffee shop and light meals",
        phone: "555-0103",
        location: "Library Commons",
        hours: "6AM - Midnight Daily",
        image: "/images/study-brew.jpg",
      },
      {
        id: "burger-bliss",
        name: "Quad Grill",
        description: "Burgers and quick bites",
        phone: "555-0104",
        location: "Central Quadrangle",
        hours: "10AM - 6PM Weekdays",
        image: "/images/quad-grill.jpg",
      },
      {
        id: "spice-emporium",
        name: "International Kitchen",
        description: "Global cuisine options",
        phone: "555-0105",
        location: "International Studies Building",
        hours: "11AM - 7PM Weekdays",
        image: "/images/international-kitchen.jpg",
      },
    ],
  },
  {
    name: "Academic Services",
    description: "Support for your academic journey",
    businesses: [
      {
        id: "bookstore",
        name: "University Bookstore",
        description: "Textbooks and academic supplies",
        phone: "555-0201",
        location: "Student Commons Building",
        hours: "9AM - 5PM Weekdays",
        image: "/images/bookstore.jpg",
      },
      {
        id: "tutoring-center",
        name: "Tutoring Center",
        description: "Peer and professional tutoring services",
        phone: "555-0202",
        location: "Learning Resource Center",
        hours: "10AM - 8PM Weekdays",
        image: "/images/tutoring.jpg",
      },
      {
        id: "tech-support",
        name: "IT Help Desk",
        description: "Technical support for students and faculty",
        phone: "555-0203",
        location: "Technology Building, Room 103",
        hours: "8AM - 6PM Weekdays",
        image: "/images/it-help.jpg",
      },
      {
        id: "writing-center",
        name: "Writing Center",
        description: "Essay and paper writing assistance",
        phone: "555-0204",
        location: "Humanities Building, Room 210",
        hours: "9AM - 7PM Weekdays",
        image: "/images/writing-center.jpg",
      },
      {
        id: "library-services",
        name: "Library Services",
        description: "Research assistance and resources",
        phone: "555-0205",
        location: "Main Library Building",
        hours: "7AM - Midnight Daily",
        image: "/images/library.jpg",
      },
    ],
  },
  {
    name: "Campus Facilities",
    description: "Essential services on campus",
    businesses: [
      {
        id: "wellness-center",
        name: "Student Health Center",
        description: "Healthcare services for students",
        phone: "555-0301",
        location: "Health Sciences Building, East Wing",
        hours: "8AM - 5PM Weekdays",
        image: "/images/health-center.jpg",
      },
      {
        id: "campus-recreation",
        name: "Recreation Center",
        description: "Gym, pool, and athletic facilities",
        phone: "555-0302",
        location: "Athletic Complex",
        hours: "6AM - 10PM Daily",
        image: "/images/rec-center.jpg",
      },
      {
        id: "career-services",
        name: "Career Services Office",
        description: "Career counseling and job placement",
        phone: "555-0303",
        location: "Student Services Building, Room 202",
        hours: "9AM - 5PM Weekdays",
        image: "/images/career-services.jpg",
      },
      {
        id: "counseling-center",
        name: "Counseling Center",
        description: "Mental health and wellness support",
        phone: "555-0304",
        location: "Student Services Building, Room 105",
        hours: "8AM - 6PM Weekdays",
        image: "/images/counseling.jpg",
      },
      {
        id: "housing-office",
        name: "Housing Office",
        description: "On-campus housing assistance",
        phone: "555-0305",
        location: "Residence Life Building",
        hours: "8:30AM - 4:30PM Weekdays",
        image: "/images/housing.jpg",
      },
    ],
  },
];

export default categories;